### ISSUE TITLE
notify_on not working

### ISSUE THREAD

**Issue by LennardWesterveld** [wantedly/step-pretty-slack-notify#21]
Hi there,

My build is successful and still getting slack notification.
So the notify_on is not working, i think the environment name is wrong.

```
    after-steps:
        - wantedly/pretty-slack-notify@0.2.11:
            webhook_url: *******
            notify_on: "failed"
            channel: ******
            username: *****
```

Result from wercker.
```
export WERCKER_PRETTY_SLACK_NOTIFY_BRANCHES=""
export WERCKER_PRETTY_SLACK_NOTIFY_NOTIFY_ON="failed"
```

**Comment by koudaiii** [comment]
Thank you for feed back :+1:
I will try :)
Please wait a little. :bow:

**Comment by dtan4** [comment]
We fixed this bug at #22 , and released as v0.2.12 :shipit: Please try this.
Thank you for reporting the issue :exclamation:

**Comment by LennardWesterveld** [comment]
Hi there is still not working for me, the exported ENV is still WERCKER_PRETTY_SLACK_NOTIFY_NOTIFY_ON i see in code thats it needs to be WERCKER_PRETTY_SLACK_NOTIFY_ON

**Comment by koudaiii** [comment]
Sorry...Thank you for feed back. :bow: 
Released v0.2.13 :exclamation: :exclamation:
